fileVersion: 1
id: "796"
mappingDefinitions:
  SOURCE_DATA:
    database: VINITHA_UDN
    schema: SRC_UDN
  TARGET_DB:
    database: VINITHA_UDN
    schema: TGT_UDN
name: New Environment Deployment
type: Environment
