fileVersion: 1
id: "515"
mappingDefinitions:
  SOURCE_DATA:
    database: RUHULAMINS_DEV
    schema: SOURCE_DATA
  TARGET_DB:
    database: RUHULAMIN_QA
    schema: TARGE4
  TARGET_DB1:
    database: RUHULAMINS_DEV
    schema: TARGET3
name: New Environment1
type: Environment
