fileVersion: 1
id: "797"
mappingDefinitions:
  SOURCE_DATA:
    database: VINITHA_UDN
    schema: SRC_UDN
  TARGET_DB:
    database: VINITHA_UDN
    schema: RETGT_UDN
name: New Environment Redeployment
type: Environment
