@id("d8c13339-e3a6-464f-89b7-c0d273e78d40")
@nodeType("1f58cb9f-3814-4120-a223-10dad03d4a91")
SELECT
     "L_ORDERKEY" AS "L_ORDERKEY",
     "L_PARTKEY" AS "L_PARTKEY",
     "L_SUPPKEY" AS "L_SUPPKEY",
     "L_LINENUMBER" AS "L_LINENUMBER",
     "L_QUANTITY" AS "L_QUANTITY",
     "L_EXTENDEDPRICE" AS "L_EXTENDEDPRICE",
     "L_DISCOUNT" AS "L_DISCOUNT",
     "L_TAX" AS "L_TAX",
     "L_RETURNFLAG" AS "L_RETURNFLAG",
     "L_LINESTATUS" AS "L_LINESTATUS",
     "L_SHIPDATE" AS "L_SHIPDATE",
     "L_COMMITDATE" AS "L_COMMITDATE",
     "L_RECEIPTDATE" AS "L_RECEIPTDATE",
     "L_SHIPINSTRUCT" AS "L_SHIPINSTRUCT",
     "L_SHIPMODE" AS "L_SHIPMODE",
     "L_COMMENT" AS "L_COMMENT",
     "L_LOAD_TIMESTAMP" AS "L_LOAD_TIMESTAMP"
FROM {{ ref('SOURCE_DATA', 'LINEITEM') }} "LINEITEM"