@id("c9ad3e22-a5f6-41ae-a2cf-cd2e0e3ac830")
@nodeType("36f5c7dd-f19d-411d-a0d9-2dc772337345")
SELECT
     "O_ORDERKEY" AS "O_ORDERKEY",
     "O_CUSTKEY" AS "O_CUSTKEY",
     "O_ORDERSTATUS" AS "O_ORDERSTATUS",
     "O_TOTALPRICE" AS "O_TOTALPRICE",
     "O_ORDERDATE" AS "O_ORDERDATE",
     "O_ORDERPRIORITY" AS "O_ORDERPRIORITY",
     "O_CLERK" AS "O_CLERK",
     "O_SHIPPRIORITY" AS "O_SHIPPRIORITY",
     "O_COMMENT" AS "O_COMMENT",
     "O_LOAD_TIMESTAMP" AS "O_LOAD_TIMESTAMP"
FROM {{ ref('SOURCE_DATA', 'ORDERS') }} "ORDERS"