@id("d4226ea4-7501-4251-b06d-e93fb95eb0a8")
@nodeType("eb41edb0-7fd7-477a-be93-ba669aa6193d")
@materializationType("view")
WITH PREP_SALES AS (
    SELECT 
        TRANSACTION_ID,
        STORE_ID,
        PRODUCT_ID,
        DATE(SALE_TIMESTAMP) AS SALE_DATE,
        MONTH(SALE_TIMESTAMP) AS SALE_MONTH,
        QUANTITY,
        COALESCE(DISCOUNT_AMOUNT, 0) AS DISCOUNT_AMOUNT
    FROM {{ ref('SOURCE_DATA', 'SOURCE_SALES') }} "SOURCE_SALES"
),

SALES_WITH_PRODUCTS AS (
    SELECT 
        S.*,
        P.PRODUCT_NAME,
        P.CATEGORY,
        (S.QUANTITY * P.BASE_PRICE) AS GROSS_REVENUE,
        ((S.QUANTITY * P.BASE_PRICE) - S.DISCOUNT_AMOUNT) AS NET_REVENUE
    FROM PREP_SALES S
    INNER JOIN  {{ ref('SOURCE_DATA', 'SOURCE_PRODUCTS') }} P ON S.PRODUCT_ID = P.PRODUCT_ID
),

ENRICHED_FINAL AS (
    SELECT 
        SWP.*,
        ST.STORE_NAME,
        ST.REGION
    FROM SALES_WITH_PRODUCTS SWP
    INNER JOIN {{ ref('SOURCE_DATA', 'SOURCE_STORES') }} ST ON SWP.STORE_ID = ST.STORE_ID
)

SELECT * FROM ENRICHED_FINAL