@id("75f58704-83b6-4079-9cf7-d384c47b2bd2")
@nodeType("eb41edb0-7fd7-477a-be93-ba669aa6193d")
SELECT
     "O_ORDERKEY" AS "O_ORDERKEY",
     "O_CUSTKEY" AS "O_CUSTKEY",
     "O_ORDERSTATUS" AS "O_ORDERSTATUS",
     "O_TOTALPRICE" AS "O_TOTALPRICE",
     "O_ORDERDATE" AS "O_ORDERDATE",
     "O_ORDERPRIORITY" AS "O_ORDERPRIORITY",
     "O_CLERK" AS "O_CLERK",
     "O_SHIPPRIORITY" AS "O_SHIPPRIORITY",
     "O_COMMENT" AS "O_COMMENT"
FROM {{ ref('SRC', 'ORDERS') }} "ORDERS"
WHERE "O_ORDERKEY" = 1