@id("54c999c1-2942-4387-8270-f0819c8be291")
@nodeType("eb41edb0-7fd7-477a-be93-ba669aa6193d")
SELECT
     "O_ORDERKEY" AS "O_ORDERKEY",
     "O_CUSTKEY" AS "O_CUSTKEY",
     "O_ORDERSTATUS" AS "O_ORDERSTATUS",
     "O_TOTALPRICE" AS "O_TOTALPRICE",
     "O_ORDERDATE" AS "O_ORDERDATE",
     "O_ORDERPRIORITY" AS "O_ORDERPRIORITY",
     "O_CLERK" AS "O_CLERK",
     "O_SHIPPRIORITY" AS "O_SHIPPRIORITY",
     "O_COMMENT" AS "O_COMMENT",
     "O_LOAD_TIMESTAMP" AS "O_LOAD_TIMESTAMP"
FROM {{ ref('SOURCE_DATA', 'ORDERS') }} "ORDERS"